[package]
name = "clapnew"
version = "0.1.0"
edition = "2024"

[dependencies]
async-recursion = "1.1.1"
clap = { version = "4.5.51", features = ["cargo", "derive"] }
io = "0.0.2"
tokio = { version = "1.48.0", features = ["full"] }
